### ISSUE TITLE
Sprint#4-T20 : Analyst should advice and guide players

### ISSUE THREAD

**Issue by hasithawaruna** [ddushan123/stock_market#25]

**Comment by IsharaLakshan** [comment]
Implementation is done. We built a lady as an analyst and she pop up in every 10 minutes.She guess the stock to we can sell from we already bought and recommend some stocks to buy.

**Comment by IsharaLakshan** [comment]
Implementation have done.we built a women as our analyst. She pops up stocks that can sell and buy to player.
